name: Build and deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_CONTAINER_APP_NAME: coralseg-containerapp
  AZURE_RESOURCE_GROUP: DSIAD
  AZURE_CONTAINER_REGISTRY: coralsegacr.azurecr.io
  IMAGE_NAME: coralseg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7E1A807984CD46D1A2877E5708951AF4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_366A543F1CF042D8AF23821EFCB793D0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7FE26F39EB3F468EB5CD1F7A76BCEF8A }}

      - name: Login to Azure Container Registry
        run: az acr login --name coralsegacr

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          containerAppName: ${{ env.AZURE_CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
