[server]
headless = true
address = "0.0.0.0"
port = 8000
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
maxMessageSize = 500
enableWebsocketCompression = false
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "light"

[client]
showErrorDetails = true
toolbarMode = "minimal"
